Repository DeveloperAcademy-POSTECH/2025-C4-M13-Visionable, pull requests merged in 2025-07, with the labels that each got.

#4 [Feat] #2 - 카메라 뷰, 모델 추가 및 카메라, 마이크, 앨범 권한 추가
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Resources/FFIP-iOS-InfoPlist.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Sources/Extensions/CMSampleBuffer+.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/CVImageBuffer+.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/Text+.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/FrameView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/VoiceSearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/ExampleUtil.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/PrivacyService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoCaptureService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoDeviceService.swift
Labels: ✨ Feat, 🌚 Frank

#8 [Feat] #7 - AsyncStream을 통한 frame 전달, 이미지 분석 요청 주기 생성
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
Labels: ✨ Feat, 🌚 Frank

#13 [Chore] #12 - 텍스트 감지 요청 주기 최적화
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
Labels: 🔧 Chore, 🌚 Frank

#15 [Feat] #10 - 동일하게 판별된 텍스트 부분만 박스 그리기 구현
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/AppRoute.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/FFIPAppRootView.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/ExampleComponent.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/View+.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VisionService.swift
  README.md
Labels: ✨ Feat, 🐻‍❄️ Mini

#19 [Feat] #14 - 카메라 기능 추가
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoCaptureService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoDeviceService.swift
Labels: ✨ Feat, 🌚 Frank

#20 [Feat] #18 - 최근 검색어 불러오기, 삭제, 눌러서 검색 구현
  FFIP-iOS/FFIP-iOS/Resources/UserDefaultsKey.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/RecentSearchCapsule.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/RecentSearchRow.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/RecentSearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
Labels: ✨ Feat, 💩 Jam

#35 [Feat] #29 - Widget
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Info.plist
  FFIP-iOS/FFIP-iOS/Resources/FFIP-iOS-InfoPlist.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/Literals/URL.swift
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Sources/App/FFIP_iOSApp.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraView.swift
  FFIP-iOS/FFIPWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  FFIP-iOS/FFIPWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  FFIP-iOS/FFIPWidget/Assets.xcassets/Contents.json
  FFIP-iOS/FFIPWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  FFIP-iOS/FFIPWidget/Assets.xcassets/ffipWidgetLogo.imageset/Contents.json
  FFIP-iOS/FFIPWidget/Assets.xcassets/ffipWidgetLogo.imageset/Group 48606.svg
  FFIP-iOS/FFIPWidget/Assets.xcassets/ffipWidgetLogo.imageset/Group 48607.svg
  FFIP-iOS/FFIPWidget/FFIPSearchWidget.swift
  FFIP-iOS/FFIPWidget/FFIPWidgetBundle.swift
  FFIP-iOS/FFIPWidget/FfipWidgetFontLiterals.swift
  FFIP-iOS/FFIPWidget/Info.plist
Labels: ✨ Feat, 🐻‍❄️ Mini

#34 [Refactor] #30 - Camera를 ExactCamera와 RelatedCamera로 분리 및 Mediator 적용
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_close.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_close.imageset/btn_camera_close.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_info.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_info.imageset/btn_camera_info.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_torch.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_torch.imageset/btn_camera_torch.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_torch_slash.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_torch_slash.imageset/btn_camera_torch_slash.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/logo_ffip.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/logo_ffip.imageset/logo_ffip.svg
  FFIP-iOS/FFIP-iOS/Resources/Literals/FontLiterals.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/AppRoute.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/FFIPAppRootView.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraHeaderBar.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraLockIcon.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipRecentSearchCapsule.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipSheet.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoDeviceService.swift
Labels: ♻️ Refactor, 🌚 Frank

#36 [Feat] #31 - SearchView Hifi 구현
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipSearchTextField.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchType.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SubViews/RecentSearchFlow.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SubViews/RecentSearchList.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SubViews/RecentSearchRow.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SubViews/SearchTypeSelectionView.swift
Labels: ✨ Feat, 💩 Jam

#42 [Feat] #39 - VoiceListenerView 추가
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/VoiceListenerView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/VoiceSearchView.swift
Labels: ✨ Feat, 🌚 Frank

#46 [Feat] #16 - 연관 탐색 UI 구현
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4 1.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4 2.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4.png
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/AppRoute.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/FFIPAppRootView.swift
  FFIP-iOS/FFIP-iOS/Sources/App/FFIP_iOSApp.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Data/ExampleModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Data/SemanticCameraCapturedImage.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/CGRect+.swift
  FFIP-iOS/FFIP-iOS/Sources/Modifiers/FfipCaptureToStackAnimationModifier.swift
  FFIP-iOS/FFIP-iOS/Sources/Modifiers/FfipKeyboardAdaptive.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/LanguageModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/CapturedImageStackView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/PhotoDetailView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/SubViews/PhotoGridView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/SubViews/PhotoPagerView.swift
  FFIP-iOS/FFIP-iOS/Sources/Prompting.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/FoundationModelService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VisionService.swift
Labels: ✨ Feat, 🐻‍❄️ Mini

#52 [Fix] #51 - Aesthetic score 삭제
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VisionService.swift
Labels: 🐛 Fix, 🌚 Frank

#47 [Feat] #40 - Exact Camera View HiFi 적용
  FFIP-iOS/FFIP-iOS/Resources/FFIP-iOS-InfoPlist.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraHeaderBar.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraTipOverlay.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCloseButton.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipSearchTextField.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/String+.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
Labels: ✨ Feat, 🌚 Frank

#56 [Feat] #50 - 연관 탐색 기능 기초 구현
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4D 1.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/AppIcon.appiconset/앱아이콘4D.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_check_disabled.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_check_disabled.imageset/icn_check_disabled.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_check_enabled.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_check_enabled.imageset/icn_check_enabled.svg
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipBoundingBox.swift
  FFIP-iOS/FFIP-iOS/Sources/Data/SemanticCameraCapturedImage.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/LanguageModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/CapturedImageAnalysisResultDTO.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/PhotoDetailView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/SubViews/PhotoGridView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/SubViews/PhotoPagerView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/FoundationModelService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VisionService.swift
Labels: ✨ Feat, 🐻‍❄️ Mini

#73 [Feat] #66 - 카메라 팝업 툴팁 기초 UI 구현
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_alertClose.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_alertClose.imageset/Frame 2085665806.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/onboarding_iPhone.svg
  FFIP-iOS/FFIP-iOS/Resources/Literals/Lottie.swift
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_scan.json
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraButton.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraHeaderBar.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraPopupTipOverlay.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipPageControl.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Onboarding/OnboardingView.swift
Labels: ✨ Feat, 🐻‍❄️ Mini

#72 [Feat] #62 - Localization 스트링 업데이트
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
Labels: ✨ Feat, 🍟Yeony

#81 [Feat] #74 - Localizable 완성
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Resources/FFIP-iOS-InfoPlist.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/Localizable.xcstrings
  FFIP-iOS/FFIP-iOS/Resources/VoiceOverLocalizable.xcstrings
Labels: 🔧 Chore, 🍟Yeony

#79 [Fix] #77 - 잡다한 버그들 죄다 해결하기
  FFIP-iOS/FFIP-iOS/Resources/Literals/AppStorageKey.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/FFIPAppRootView.swift
  FFIP-iOS/FFIP-iOS/Sources/App/FFIP_iOSApp.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipSearchTextField.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipSheet.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipToolTip.swift
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipUIKitTextField.swift
  FFIP-iOS/FFIP-iOS/Sources/Extensions/UITextField+.swift
  FFIP-iOS/FFIP-iOS/Sources/Modifiers/FfipSheetModifier.swift
  FFIP-iOS/FFIP-iOS/Sources/Modifiers/FfipToolTipModifier.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Onboarding/OnboardingView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SubViews/SearchTypeSelectionView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/VoiceSearchView.swift
Labels: 🐛 Fix, 🐻‍❄️ Mini

#83 [Feat] #75 - Tooltip Lottie 추가
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/onboarding_iPhone.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/onboarding_iPhone.svg
  FFIP-iOS/FFIP-iOS/Resources/Literals/Lottie.swift
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_green.json
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_grid.json
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_grid2.json
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_tap.json
  FFIP-iOS/FFIP-iOS/Resources/Lotties/toolTip_zoom.json
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraPopupTipOverlay.swift
Labels: ✨ Feat, 💩 Jam

#78 [Feat] #76 - 파운데이션 프롬프트 변형
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/FoundationModelService.swift
Labels: ✨ Feat, 🌚 Frank

#84 [Chore] #80 - 최소 지원 버전 iOS 18.0으로 마이그레이션
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Resources/Literals/URL.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/AppCoordinator.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/AppRoute.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Coordinator/FFIPAppRootView.swift
  FFIP-iOS/FFIP-iOS/Sources/App/FFIP_iOSApp.swift
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/LanguageModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Search/SearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/iOS18/VoiceSearchSupportVersionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/iOS18/VoiceSearchSupportVersionView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/iOS26/VoiceSearchModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/iOS26/VoiceSearchView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/FoundationModelService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/SpeechRecognitionService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/SpeechTranscribtionService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VisionService.swift
  FFIP-iOS/FFIPWidget/FFIPSearchWidget.swift
  FFIP-iOS/FFIPWidget/FFIPWidgetBundle.swift
Labels: 🔧 Chore, 🐻‍❄️ Mini

#88 [Fix] #87 - 온보딩 onboardingText 중복 생성 문제 해결
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Onboarding/OnboardingView.swift
Labels: 🐛 Fix, 🐻‍❄️ Mini

#92 [Fix] #89 - 팀 QA 내용 반영
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/btn_camera_close.imageset/btn_camera_close.svg
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/icn_settings_voice_noDark.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/Contents.json
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/onboarding_iPhone@2x.png
  FFIP-iOS/FFIP-iOS/Resources/Assets.xcassets/onboarding_iPhone.imageset/onboarding_iPhone@3x.png
  FFIP-iOS/FFIP-iOS/Sources/App/Factory/ModuleFactory.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/PhotoDetail/SubViews/PhotoPagerView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/VoiceSearch/iOS26/VoiceSearchView.swift
Labels: 🐛 Fix, 🐻‍❄️ Mini

#91 [Fix] #82 - asyncstream 두 개로 분리, 팀 QA 반영
  FFIP-iOS/FFIP-iOS.xcodeproj/project.pbxproj
  FFIP-iOS/FFIP-iOS/Sources/Components/FfipCameraHeaderBar.swift
  FFIP-iOS/FFIP-iOS/Sources/Modifiers/FfipToastMessageModifier.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraMediator.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/ExactCamera/ExactCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/CameraModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/Models/VisionModel.swift
  FFIP-iOS/FFIP-iOS/Sources/Presentation/Camera/SemanticCamera/SemanticCameraView.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/SpeechTranscribtionService.swift
  FFIP-iOS/FFIP-iOS/Sources/Utils/VideoDeviceService.swift
Labels: 🐛 Fix, 🌚 Frank
